### ISSUE TITLE
Question about parameters

### ISSUE THREAD

**Issue by diegogarcia101** [dynverse/dynmethods#147]
Hello, I am using your excellent package in a project and in your code you reference a parameters file:

"/ti/input/params.json"

Is this file available?  I have looked around and cannot find it and it would be most helpful as I am looking at some of your methods in detail.  For example, what distinguishes "PAGA" from "PAGA Tree"?

Thanks very much in advance,

Jonathan Greene

**Comment by zouter** [comment]
Hi Jonathan!

This file will be mounted inside the docker based on the parameters you give to `infer_trajectory`. For each method, you can check out these parameters using `?dynmethods::ti_paga` and `?dynmethods::ti_paga_tree`.

It's true that the difference between these methods is currently not discussed in the documentation. This is on our to-do list!

The difference between ti_paga and ti_paga_tree is that the latter uses the minimal spanning tree, while paga uses a cutoff on the connectivity matrix.
```
105c105
<   np.triu(adata.uns["paga"]["connectivities"].todense(), k = 0),
---
>   adata.uns["paga"]["connectivities_tree"].todense(),
110c110
< milestone_network = milestone_network.query("length >= " + str(params["connectivity_cutoff"])).reset_index(drop=True)
---
> milestone_network = milestone_network.query("length > 0").reset_index(drop=True)
```

**Comment by diegogarcia101** [comment]
Thanks very much, this information is very helpful.

Best regards,

Jonathan

**Comment by zouter** [comment]
Great! Thanks

Wouter
