### ISSUE TITLE
SCORPIUS

### ISSUE THREAD

**Issue by zouter** [dynverse/dynmethods#17]
Hello @rcannood, @zouter and @saeyslab

This issue is for discussing the wrapper for your trajectory inference method, SCORPIUS, which we wrapped for our benchmarking study ([10.1101/276907](https://doi.org/10.1101/276907)). In our [dynmethods](https://github.com/dynverse/dynmethods) framework, we collected some meta information about your method, and created a docker wrapper so that all methods can be easily run and compared. The code for this wrapper is located in docker containers[[1]](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius)[[2]](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius_sparse). The way this container is structured is described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html).

We created 2 separate wrappers:
- [**SCORPIUS**](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius): Regular version
- [**SCORPIUS sparse**](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius_sparse): Using landmark MDS

We are creating this issue to ensure your method is being evaluated in the way it was designed for. The checklist below contains some important questions for you to have a look at.

- [x] **Parameters**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius/definition.yml) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#parameters))
  - Are all important parameters described in this file?
  - For each parameter, is the proposed default value reasonable?
  - For each parameter, is the proposed parameter space reasonable (e.g. lower and upper boundaries)?
  - Is the description of the parameters correct and up-to-date?
- [x] **Input**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius/definition.yml) and loaded in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#input))
  - Is the correct type of expression requested (raw counts or normalised expression)?
  - Is all prior information (required or optional) requested?
  - Would some other type of prior information help the method?
- [x] **Output**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius/definition.yml) and saved in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#output))
  - Is the output correctly processed towards the [common trajectory model](https://github.com/dynverse/dynwrap#dynwrap)? Would some other postprocessing method make more sense?
  - Is all relevant output saved (dimensionality reduction, clustering/grouping, pseudotime, ...)
- [x] **Wrapper script**, see [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#doing-trajectory-inference))
  - This is a script that is executed upon starting the docker container. It will receive several input files as defined by `definition.yml`, and is expected to produce certain output files, also as defined by `definition.yml`.
  - Is the script a correct representation of the general workflow a user is expected to follow when they want to apply your method to their data?
- [x] **Quality control**, see [the qc worksheet](https://docs.google.com/spreadsheets/d/1GWWdndfTPtXPsCXK07jU03MmhIJHmv28E7YiMnQ_0Xo//edit#gid=1141959983)
  - We also evaluated the implementation of a method based on a large check list of good software software development practices.
  - Are the answers we wrote down for your method correct and up to date? Do you disagree with certain answers? (Feel free to leave a comment in the worksheet)
    - You can improve the QC score of your method by implementing the required changes and letting us know. *Do not gloss over this, as it is the easiest way to improve the overall ranking of your TI method in our study!*

The most convenient way for you to test and adapt the wrapper is to install [dyno](https://github.com/dynverse/dyno), download and modify [these files](https://github.com/dynverse/dynmethods/tree/master/containers/scorpius), and run your method on a dataset of interest or one of our synthetic toy datasets. This is further described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html). Once finished, we prefer that you [fork the dynmethods repository](https://github.com/dynverse/dynmethods), make the necessary changes, and send us a pull request. Alternatively, you can also send us the files and we will make the necessary changes.

If you have any further questions or remarks, feel free to reply to this issue.

Kind regards,
@rcannood and @zouter

**Comment by rcannood** [comment]
In response to this ticket, I made the following changes to SCORPIUS:
* Code coverage is now being assessed
* The repository now incorporates a devel branch, and uses the 'releases' functionality of SCORPIUS to post released versions.
