### ISSUE TITLE
tSpace

### ISSUE THREAD

**Issue by zouter** [dynverse/dynmethods#19]

**Comment by zouter** [comment]
I am able to run `tSpace` on our test data using:

```r
library(tSpace)
library(tictoc)
tSpace::tSpace(t(task$expression))
```

However it is unclear how to extract a trajectory from the output. I can find the dimensionality reduction in the output, and also the distances from waypoints to each cells. But I cannot find the topology.

Perhaps @hylasD can help?

**Comment by hylasD** [comment]
Hi zouter, 

thank you for pointing that tictoc is missing from Description file. I just updated package and fixed that.

At the moment visualization of trajectory matrix using PCA or t-SNE (ts_file in the output list) allows user to see all existing trajectories, however user needs to select/gate out manually (e.g. in R or FlowJo) a desired trajectory (please take a look at Fig. 1e and Fig. 3b-c in the original manuscript doi: https://doi.org/10.1101/336313). 

Once trajectory is isolated I recommend to select several cells at the putative origin of the trajectory and find trajectories starting from these cells, which are stored in tspace_matrix (third object within the output list). 

In case of single cell RNAseq I recommend calculating "ground truth" tspace_matrix (trajectories for all cells within the dataset). If you use CyTOF profiles with +10000 cells we find that approximation (calculating 100-1000 trajectories) works just fine and in that case average values of closest 3-5 trajectories originating from the isolated trajectory start are your trajectory distances that you can use for cell alignment. We described isolation process in Materials and methods - Supplemental info (https://www.biorxiv.org/content/biorxiv/suppl/2018/06/01/336313.DC1/336313-1.pdf)

I'm working on including option to fit multiple lines into unfolded trajectory manifold, so the users won't need to manually isolate trajectories in future. If you still have issues I can take a look at your output and help out.

**Comment by rcannood** [comment]
Thanks for your input, @hylasD.

I had a look at tSpace as well ([link](https://github.com/dynverse/dynmethods/blob/feature/add_tspace/containers/tspace/run.R)). For now, tSpace indeed does not seem to include any algorithmic trajectory inference yet, so it cannot be included in dynmethods.

Please let us know if tSpace is updated to include an automated trajectory inference step.

Kind regards,
Robrecht
