### ISSUE TITLE
DPT

### ISSUE THREAD

**Issue by rcannood** [dynverse/dynmethods#32]
Hello Laleh, @flying-sheep and @theislab

This issue is for discussing the wrapper for your trajectory inference method, DPT, which we wrapped for our benchmarking study ([10.1101/276907](https://doi.org/10.1101/276907)). In our [dynmethods](https://github.com/dynverse/dynmethods) framework, we collected some meta information about your method, and created a docker wrapper so that all methods can be easily run and compared. The code for this wrapper is located in [a docker container](https://github.com/dynverse/dynmethods/tree/master/containers/dpt). The way this container is structured is described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html).

We are creating this issue to ensure your method is being evaluated in the way it was designed for. The checklist below contains some important questions for you to have a look at.

- [ ] **Parameters**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/dpt/definition.yml) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#parameters))
  - Are all important parameters described in this file?
  - For each parameter, is the proposed default value reasonable?
  - For each parameter, is the proposed parameter space reasonable (e.g. lower and upper boundaries)?
  - Is the description of the parameters correct and up-to-date?
- [ ] **Input**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/dpt/definition.yml) and loaded in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/dpt/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#input))
  - Is the correct type of expression requested (raw counts or normalised expression)?
  - Is all prior information (required or optional) requested?
  - Would some other type of prior information help the method?
- [x] **Output**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/dpt/definition.yml) and saved in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/dpt/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#output))
  - Is the output correctly processed towards the [common trajectory model](https://github.com/dynverse/dynwrap#dynwrap)? Would some other postprocessing method make more sense?
  - Is all relevant output saved (dimensionality reduction, clustering/grouping, pseudotime, ...)
- [ ] **Wrapper script**, see [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/dpt/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#doing-trajectory-inference))
  - This is a script that is executed upon starting the docker container. It will receive several input files as defined by `definition.yml`, and is expected to produce certain output files, also as defined by `definition.yml`.
  - Is the script a correct representation of the general workflow a user is expected to follow when they want to apply your method to their data?
- [ ] **Quality control**, see [the qc worksheet](https://docs.google.com/spreadsheets/d/1GWWdndfTPtXPsCXK07jU03MmhIJHmv28E7YiMnQ_0Xo//edit#gid=1260265548)
  - We also evaluated the implementation of a method based on a large check list of good software software development practices.
  - Are the answers we wrote down for your method correct and up to date? Do you disagree with certain answers? (Feel free to leave a comment in the worksheet)
    - You can improve the QC score of your method by implementing the required changes and letting us know. *Do not gloss over this, as it is the easiest way to improve the overall ranking of your TI method in our study!*

The most convenient way for you to test and adapt the wrapper is to install [dyno](https://github.com/dynverse/dyno), download and modify [these files](https://github.com/dynverse/dynmethods/tree/master/containers/dpt), and run your method on a dataset of interest or one of our synthetic toy datasets. This is further described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html). Once finished, we prefer that you [fork the dynmethods repository](https://github.com/dynverse/dynmethods), make the necessary changes, and send us a pull request. Alternatively, you can also send us the files and we will make the necessary changes.

If you have any further questions or remarks, feel free to reply to this issue.

Kind regards,
@rcannood and @zouter

**Comment by flying-sheep** [comment]
Hi! So first, I’m not Laleh. I’m [Philipp](https://orcid.org/0000-0002-0369-2888), the author of the destiny package and paper, but not the DPT paper. Laleh has no GitHub account afaik.

Parameters: Seem reasonable, I’m just missing `k`, the number of nearest neighbors.

Input: destiny’s DPT implementation needs variance-stabilized expressions (e.g. `log1p(counts)`)

Output: Seems good.

Wrapper script: Good, except that you should use destiny’s methods instead of `@field` access (e.g. `eigenvectors(dm)`. Also we use [kbranches](https://github.com/theislab/kbranches) instead of destiny’s branch separation. (i should formally integrate it and deprecate the old branching)

QC:
- L27&29: I use feature branches for bigger things, but that hasn’t been necessary recently. I want a 1 there 😉
- L35: All parameters are fully documented, which is tested by CI. Also needs a 1.
- L42: Currently I *do* have some warnings for the incomplete support of sparse data. I hope I can fix this soon 😄. I deserve less than a 1 here I think.
- L43: I don’t see why there’s effort to extract information. There should be methods for everything. Could you please elaborate here?

**Comment by rcannood** [comment]
Hi Philipp,

Thanks for responding so quickly!

* **Definition**: Sorry about that ─ I know you're Philipp, and that Laleh has no github account. I'm not sure how this mistake got in there (probably sleep deprevation is to blame).
* **Parameters**: The `k` parameter was indeed a bit of an issue, since its default value depends on the dataset, namely `k = find_dm_k(dataset_n_observations(data, distance) - 1L),`. What I can do, is add two parameters. Would this be ok for you?
  - one logical parameter `auto_find_k`, if true it will set `k` to `find_dm_k`. By default it's true.
  - one integer parameter `k`. What are the lower and upper bounds for this parameter?
* **Input**: So you would prefer `DiffusionMap` to be run using raw counts but log transformed (`data = log1p(counts)`), instead of normalised log-transformed expression data (`data = expression`)?
* **Wrapper script**: Alright! Cool, I didn't know about kbranches. Would you like to wait for this until kbrances is properly integrated into destiny? Could you propose some changes for the script as part of a pull request?
* **QC**: Before changing any of the QC scores, I have a few questions:
  - L27: I don't see a development branch (similar to what is discussed [here](https://nvie.com/posts/a-successful-git-branching-model/). Having a separate development branch is important because this way, you can add new features on the development branch, and only when you believe that there are no issues with a certain version of your software (using travis or something else), you push the code to the master. That way, end-users like @zouter and me will never encounter problems with the master branch of destiny.
  - L29: I don't see any branches related to the development of specific features [link](https://github.com/theislab/destiny/branches/all). If there is only a small amount of developers working on this project, you might indeed not need it. If it's any consolation, no other TI methods received a '1' for this question. I think this is simply because software packages for inferring trajectories are still often developed by just a handful of people.
   - L35: I agree most parameters are fully documented. However, we have a few people using destiny on a regular basis, and one part of the documentation that really trips people up is this part: "...  All parameters after this have to be specified by name". What are parameters can you even pass using the ...'s?
   - L42: This is not an issue yet on Bioconductor, right? 
   - L43: The question was perhaps not clearly formulated. It's to do with how easy it was to transform the data produced by DPT into a the same format as the rest of the TI methods. At the time the wrapper was written, I spent quite some time thinking on how I can calculate to what extent one cell belongs to each of the tips (e.g. cell 1 is 0.43 tip1, 0.11 tip2, 0.02 tip3, and 0.44 center ─ these values should sum to 1). The problem is that DPT provides me with distances from each cell to each of the tips, but this would have to be transformed to percentages, somehow. Do you think that with the integration of`kbranches`, this problem could be solved?

Robrecht

**Comment by flying-sheep** [comment]
Parameterwise, I often go this route: accept `ParameterType`|`NULL`, and if NULL is specified, use a default (which can be sophisticated as in this case). that’s because using two parameters is imho confusing: if the k is set, and auto_find_k too, what does that mean? i know it’s easy to document, but i like to encode things into types instead of people’s brains.

The boundaries for k are min: 1, max: (n_cells-1).

- **Input**: normalised log-transformed expression data is also fine, sorry that i misunderstood!
- **Wrapper**: IDK if i’d get around to any of that soon, sorry 😢 but kbranches has a super simple API!
- **QC**:
    - L27: master *is* the development branch. the bioconductor channel tracking master is called “devel” and not guaranteed stable. if they want a stable version, people use the newest bioconductor release’s version (destiny 2.10 i think).
    - L29: i delete feature branches after merging them into master. i think everyone does that :wink:
    - L35: oh! i think i should have phrased that better! “All parameters after this have to be specified by name” means that the `...` only serves to stop positional parameters, and in fact i throw and error if further parameters are specified! see [here](https://github.com/theislab/destiny/blob/e322cc702355f943d90039513b15338f567a7381/R/dpt.r#L41-L42). every API with more than like 3 positional parameters becomes hard, so i elect to force people to specify unimportant ones by name.
    - L42: it should by now, but only if you specify sparse expression matrices.
    - L43: i see! indeed, there’s no cluster probabilites, but i think that’s conceptual. kbranches returns quite some info: https://github.com/theislab/kbranches/blob/45392f91139f699da14d0fea60867f87c4595de1/R/kbranches-global.R#L25-L44

**Comment by rcannood** [comment]
* **Parameters**: The problem is that we're using [ParamHelpers::makeDiscreteParam](https://www.rdocumentation.org/packages/ParamHelpers/versions/1.10/topics/Param) behind the screens to define each of the parameters, so that in the near future we could attempt to optimise the parameters using [mlrMBO](https://cran.r-project.org/web/packages/mlrMBO/vignettes/mlrMBO.html). However, I understand that this approach is indeed commonly used in R, where a parameter could have an integer as value, or NULL. @zouter and I discussed it briefly, and I think we could develop a solution for this relatively quickly. I've created an issue at dynverse/dynwrap#41 and will keep you updated. Is this ok?
* **Input**: Ok!
* **QC L27**: Okay, let's assume that the bioconductor repository can count for the stable branch and the github repository for the development branch. I changed it to a 1.
* **QC L29**: I thought they were still listed on github even after deletion, but I'm wrong on this matter. I changed this score to a 1.
* **QC L35**: Ha! I like that. A 'strict' version of R would be nice. Now I understand what you mean by "All parameters after this have to be specified by name". I changed the value for this score to a 1 :) Perhaps it would be an idea to specifically mention in the documentation that the '...' should not be used for anything, as well as present the user with a reasonable error message in case `stopifnot` is triggered.
* **Wrapper** and **QC L43**: I'm starting to like kbranches :) I'll leave L43 as is, for now, until either of us have had the time of looking at implementing kbranches.

**Comment by flying-sheep** [comment]
> I've created an issue at dynverse/dynwrap#41 and will keep you updated. Is this ok?

yeah, thank you!

> Perhaps it would be an idea to specifically mention in the documentation that the '...' should not be used for anything, as well as present the user with a reasonable error message in case stopifnot is triggered?

definitely! i’ll do that.

> I'll leave L43 as is, for now, until either of us have had the time of looking at implementing kbranches.

OK! maybe @nchlis is interested!

---

great, i guess everything is cleared up now :smile:

**Comment by flying-sheep** [comment]
fixed in theislab/destiny@93306a33978f805bf6b59ec867bdea1aed08f81e

**Comment by rcannood** [comment]
Hi Philipp,

I was looking at kbranches just now. I can see how kbranches nicely identifies tip points, branching points, as well as cluster different regions. However, I'm not sure how to turn this into a trajectory.

[Here](https://github.com/dynverse/dynmethods/blob/feature/add_kbranches/containers/kbranches/run.R#L65) is an initial script. I found I can identify tip points, but if I try to apply DPT afterwards, I get told `you need to specify 1-3 tips, got 4`.

Could you shed some light on how this might be turned into a trajectory-like format?

Robrecht

**Comment by flying-sheep** [comment]
@nchlis might be of most help here!

**Comment by nchlis** [comment]
Hi everyone,

kbranches can find an arbitrary number of tips.
If I remember correctly the original DPT code (pre-destiny) uses 3 cells/tips to calculate correlation/anticorrelation and branching. It then recursively searches for more tips.

So to use destiny::DPT as is, maybe you need to manually subsample 3 tips?

Best,
Nikos

**Comment by rcannood** [comment]
Hi Nikos,

Thanks for your input! I will wait with adding DPT+kbranches to dynmethods until they are compatible with eachother.

Kind regards,
Robrecht

**Comment by flying-sheep** [comment]
Ooh, I’m stupid, the error was in the DPT code, not kbranches. Sorry Nikos!

They are compatible, but `DPT(..., tips = ...)` means to use the built-in branch finding of DPT.

If you want to plot the kbranches segmentation, you can do `plot(dm, col = tips$cluster)`

**Comment by rcannood** [comment]
This would only produce a plot with a diffusion maps dimensionality reduction coloured with the clusters found by kbranches; not a trajectory, no?

**Comment by nchlis** [comment]
yes!

**Comment by rcannood** [comment]
Closing this issue. Yes, I did mean the dpt order. If you believe it would be interesting to add kbranches or something similar, feel free to create a new issue.
