### ISSUE TITLE
CellTrails

### ISSUE THREAD

**Issue by rcannood** [dynverse/dynmethods#80]
Hello @dcellwanger

This issue is for discussing the wrapper for your trajectory inference method, CellTrails, which we wrapped for our benchmarking study ([10.1101/276907](https://doi.org/10.1101/276907)). In our [dynmethods](https://github.com/dynverse/dynmethods) framework, we collected some meta information about your method, and created a docker wrapper so that all methods can be easily run and compared. The code for this wrapper is located in [a docker container](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails). The way this container is structured is described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html).

We are creating this issue to ensure your method is being evaluated in the way it was designed for. The checklist below contains some important questions for you to have a look at.

- [ ] **Parameters**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails/definition.yml) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#parameters))
  - Are all important parameters described in this file?
  - For each parameter, is the proposed default value reasonable?
  - For each parameter, is the proposed parameter space reasonable (e.g. lower and upper boundaries)?
  - Is the description of the parameters correct and up-to-date?
- [ ] **Input**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails/definition.yml) and loaded in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#input))
  - Is the correct type of expression requested (raw counts or normalised expression)?
  - Is all prior information (required or optional) requested?
  - Would some other type of prior information help the method?
- [ ] **Output**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails/definition.yml) and saved in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#output))
  - Is the output correctly processed towards the [common trajectory model](https://github.com/dynverse/dynwrap#dynwrap)? Would some other postprocessing method make more sense?
  - Is all relevant output saved (dimensionality reduction, clustering/grouping, pseudotime, ...)
- [ ] **Wrapper script**, see [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#doing-trajectory-inference))
  - This is a script that is executed upon starting the docker container. It will receive several input files as defined by `definition.yml`, and is expected to produce certain output files, also as defined by `definition.yml`.
  - Is the script a correct representation of the general workflow a user is expected to follow when they want to apply your method to their data?
- [ ] **Quality control**, see [the qc worksheet](https://docs.google.com/spreadsheets/d/1GWWdndfTPtXPsCXK07jU03MmhIJHmv28E7YiMnQ_0Xo//edit#gid=1837334636)
  - We also evaluated the implementation of a method based on a large check list of good software software development practices.
  - Are the answers we wrote down for your method correct and up to date? Do you disagree with certain answers? (Feel free to leave a comment in the worksheet)
    - You can improve the QC score of your method by implementing the required changes and letting us know. *Do not gloss over this, as it is the easiest way to improve the overall ranking of your TI method in our study!*

The most convenient way for you to test and adapt the wrapper is to install [dyno](https://github.com/dynverse/dyno), download and modify [these files](https://github.com/dynverse/dynmethods/tree/master/containers/celltrails), and run your method on a dataset of interest or one of our synthetic toy datasets. This is further described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html). Once finished, we prefer that you [fork the dynmethods repository](https://github.com/dynverse/dynmethods), make the necessary changes, and send us a pull request. Alternatively, you can also send us the files and we will make the necessary changes.

If you have any further questions or remarks, feel free to reply to this issue.

Kind regards,
@zouter and @rcannood

**Comment by dcellwanger** [comment]
Hello @rcannood and @zouter,

Thanks for considering CellTrails in your work. I am very sorry for my late response - I was out of office. We will have a look into your requests. What is your anticipated project timeline?

Best wishes

**Comment by zouter** [comment]
Hi @dcellwanger 

Thank you for your response!

Our current timeline is that we would generate the final benchmarking results from the 6th of august onwards.

Wouter

**Comment by rcannood** [comment]
Hello Daniel,

Thanks for getting back in touch with us. I have a had a look at your comments and modified the QC scores accordingly.

Kind regards,
Robrecht

### QC23
QC23 (continuous integration): 0 → 1
If you like, you can add code coverage quite easily as well, by adding the following code to your `.travis.yml`. This would increase the QC24 from 0 to 1 as well.
```
r_packages:
 - covr
after_success:
 - R CMD BiocCheck .
 - R -e 'covr::codecov()'
```
### QC34 and QC49
QC34 (tutorial datasets): 0 → 1
QC49 (paper datasets): 0.25 → 1
I see! This was an oversight on our part.

### QC20
QC20 (dummy proofing): 0 → 1
I had a closer look through the code and indeed saw dummy proofing for various exposed functions

**Comment by dcellwanger** [comment]
Hello Robrecht, 

**Q24,25**
Current [code coverage](https://codecov.io/gh/dcellwanger/CellTrails) = 81.63%

**Q28,29**
Version numbering and separation in devel/stable branches is somewhat tied to _Bioconductor_'s life cycle (see [Version Numbering](http://bioconductor.org/developers/how-to/version-numbering/)), and therefore, meeting this criteria disadvantages novel _Bioconductor_ packages.

Since its recent acceptance at _Bioconductor_, `CellTrails` was only listed at _Bioconductor_'s devel branch. I would argue that the code at _GitHub_ represents the developmental version, while the code at _Bioconductor_ is the stable version. Please note that `CellTrails` had, indeed, several minor releases (see [NEWS](https://github.com/dcellwanger/CellTrails/blob/master/NEWS)). 

Biannually the _Bioconductor_ devel branch becomes the _Bioconductor_ release branch (in mid-April and mid-October). This will automatically generate a developmental branch of `CellTrails` at _Bioconductor_ (mirrored at _GitHub_), where new features are introduced, and a stable branch of `CellTrails` at _Bioconductor_, respectively. Package version numbering is performed accordingly (see link above).

-Daniel

**Comment by rcannood** [comment]
QC24: Nice! I updated it in the QC worksheet.

QC28,29: Fair enough. I will discuss this with @zouter. Perhaps all the bioconductor packages should get a score of 1 for this question. I

**Comment by rcannood** [comment]
Hi Daniel,

QC28,29: We've changed the values of these scores to '1' for all bioconductor packages. This results in CellTrails having a near-perfect QC score.

I'm closing this issue for now. If you have any further comments on the CellTrails wrapper, feel free to create a new issue or pull request.

Robrecht
