### ISSUE TITLE
Libraries missing from std R insallation:

### ISSUE THREAD

**Issue by stela2502** [dynverse/dynmethods#86]
HI team,
when I tried to install your lib I am missing these libs from my R installation:
magrittr
dynutils
It would probably make sense to add it into your depends file ;-)

Best,
Stefan

**Comment by zouter** [comment]
Hi!

Thank you for trying out the package!
Quite a strange error you're getting, as [magrittr and dynutils are already included in the dependencies](https://github.com/dynverse/dynmethods/blob/master/DESCRIPTION#L32).

Probably something went wrong during the installation. Are you able to install the package now?

**Comment by zouter** [comment]
Hope everything works fine for you now. Closing this for now.
